--- 

- hosts: localhost
  become: yes
  vars:
    - vars/main.yml
  tasks:
    - name: "Add vscodium repo key"
      apt_key:
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        state: present

    - name: "Add vscodium repo"
      apt_repository:
        repo: deb https://download.vscodium.com/debs vscodium main
        state: present

    - name: "Update the system"
      apt: upgrade=dist force_apt_get=yes

    - name: "Install default packages"
      apt:
        name:
          - vim
          - git
          - codium
          - terminator
          - tmux
          - zsh
          - wget
          - fonts-powerline
    
    - name: "Download ohmyzsh install script"
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh

    - name: "Install ohmyzsh"
      become: no
      script: /tmp/ohmyzsh.sh
      args:
        creates: /home/{{ user }}/.oh-my-zsh/LICENSE.txt

    - name: "update ohmyzsh theme to agnoster"
      become: no
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="agnoster"'

    - name: "Add oh-my-tmux git repo"
      git:
        repo: https://github.com/gpakosz/.tmux.git
        dest: /home/{{ user }}/.tmux
    
    - name: "Create ohmytmux symlink"
      file:
        src: "/home/{{ user }}/.tmux/.tmux.conf"
        dest: "/home/{{ user }}/tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: link
        
    - name: "Copy tmux.conf.local from ohmytmux conf"
      copy:
        src: "/home/{{ user }}/.tmux/.tmux.conf.local"
        dest: "/home/{{ user }}/.tmux.conf.local"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "start tmux as default"
      lineinfile:
        path: /home/{{ user}}/.zshrc
        regexp: 'if [ -z "$TMUX" ] ; then;  tmux attach -t TMUX || tmux new -s TMUX; fi'
        line: 'if [ -z "$TMUX" ] ; then;  tmux attach -t TMUX || tmux new -s TMUX; fi'
        state: present
        insertafter: EOF
        create: True


    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: "Alias code to codium"
      become: no
      lineinfile:
        path: "/home/{{ user}}/.zshrc"
        regexp: '^alias code='
        line: 'alias code="codium"'
        state: present
        insertafter: EOF
        create: True